[package]
name = "rawtojpg"
edition = "2021"
version = "0.3.2"
authors = ["Chris Down <chris@chrisdown.name>"]
description = "A very fast embedded JPEG extractor from RAW files."
repository = "https://github.com/cdown/rawtojpg"
readme = "README.md"
keywords = ["raw", "camera", "extract", "jpeg", "jpg"]
categories = ["command-line-utilities"]
license = "MIT"

[dependencies]
anyhow = "1.0.83"
futures = "0.3.30"
memmap2 = "0.9.4"
rexif = "0.7.3"

[dependencies.clap]
version = "4.3.0"
features = ["std", "derive", "help"]
default-features = false

[dependencies.nix]
version = "0.28.0"
features = ["feature", "fs", "mman"]
default-features = false

[dependencies.tokio]
version = "1.37.0"
features = ["fs", "io-util", "macros", "rt-multi-thread"]
default-features = false

[dependencies.tokio-stream]
version = "0.1.15"
features = ["fs"]
default-features = false
